baseURL = 'https://thebigby10.github.io/'
languageCode = 'en-us'
title = 'ThebigbyXX_kb'
theme = 'PaperMod'

# Enables the creation of the search index file
[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
    # Shows the search icon in the header
    ShowSearch = true

[[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 5

[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 10

[[menu.main]]
    name = "Learnings"
    identifier = "learnings"
    url = "/learnings/"
    weight = 20

[[menu.main]]
    name = "DevOps"
    parent = "learnings"
    url = "/learnings/devops/"
    weight = 1

[[menu.main]]
    name = "Backend Development"
    parent = "learnings"
    url = "/learnings/backend/"
    weight = 1

[[menu.main]]
    name = "Experiments"
    url = "/experiments/"
    weight = 30
