baseURL = 'https://thebigby10.github.io/'
languageCode = 'en-us'
title = 'ThebigbyXX_kb'
theme = 'PaperMod'

[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 10

[[menu.main]]
    name = "Learnings"
    identifier = "learnings"
    url = "/learnings/"
    weight = 20

[[menu.main]]
    name = "DevOps"
    parent = "learnings"
    url = "/learnings/devops/"
    weight = 1

[[menu.main]]
    name = "Backend Development"
    parent = "learnings"
    url = "/learnings/backend/"
    weight = 1

[[menu.main]]
    name = "Experiments"
    url = "/experiments/"
    weight = 30
